src/Entity/AttributeProduct.php
<?php

namespace App\Entity;

use App\Repository\AttributeProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AttributeProductRepository::class)
 */
class AttributeProduct
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $product_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $attribute_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $value;
    /**
     * @var
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="attributeProduct")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="product_id", referencedColumnName="id")
     * })
     */
    private $products;

    /**
     * @var
     * @ORM\ManyToOne(targetEntity="App\Entity\Attribute", inversedBy="attributeProduct")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="attribute_id", referencedColumnName="id")
     * })
     */
    private $attributes;

    /**
     * Products constructor.
     */
    public function __construct()
    {
        $this->attributes = new ArrayCollection();
        $this->products = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductId(): ?int
    {
        return $this->product_id;
    }

    public function setProductId(int $product_id): self
    {
        $this->product_id = $product_id;

        return $this;
    }

    public function getAttributeId(): ?int
    {
        return $this->attribute_id;
    }

    public function setAttributeId(int $attribute_id): self
    {
        $this->attribute_id = $attribute_id;

        return $this;
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function setValue(string $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getAttributes()
    {
        return $this->attributes;
    }
}

src/Form/AttributeProductType.php
<?php

namespace App\Form;

use App\Entity\AttributeProduct;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AttributeProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('product_id')
            ->add('attribute_id')
            ->add('value')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AttributeProduct::class,
        ]);
    }
}

src/Admin/Controller/AttributeProductController.php
<?php

namespace App\Admin\Controller;

use App\Entity\AttributeProduct;
use App\Form\AttributeProductType;
use App\Repository\AttributeProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/attribute/product", name="AttributeProductController")
 */
class AttributeProductController extends AbstractController
{
    /**
     * @Route("/", name="attribute_product_index", methods={"GET"})
     * @param AttributeProductRepository $attributeProductRepository
     * @return Response
     */
    public function index(AttributeProductRepository $attributeProductRepository): Response
    {
        return $this->render('admin/attribute_product/index.html.twig', [
            'attribute_products' => $attributeProductRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="attribute_product_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $attributeProduct = new AttributeProduct();
        $form = $this->createForm(AttributeProductType::class, $attributeProduct);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($attributeProduct);
            $entityManager->flush();

            return $this->redirectToRoute('attribute_product_index');
        }

        return $this->render('admin/attribute_product/new.html.twig', [
            'attribute_product' => $attributeProduct,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="attribute_product_show", methods={"GET"})
     * @param AttributeProduct $attributeProduct
     * @return Response
     */
    public function show(AttributeProduct $attributeProduct): Response
    {
        return $this->render('admin/attribute_product/show.html.twig', [
            'attribute_product' => $attributeProduct,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="attribute_product_edit", methods={"GET","POST"})
     * @param Request $request
     * @param AttributeProduct $attributeProduct
     * @return Response
     */
    public function edit(Request $request, AttributeProduct $attributeProduct): Response
    {
        $form = $this->createForm(AttributeProductType::class, $attributeProduct);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('attribute_product_index');
        }

        return $this->render('admin/attribute_product/edit.html.twig', [
            'attribute_product' => $attributeProduct,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="attribute_product_delete", methods={"DELETE"})
     * @param Request $request
     * @param AttributeProduct $attributeProduct
     * @return Response
     */
    public function delete(Request $request, AttributeProduct $attributeProduct): Response
    {
        if ($this->isCsrfTokenValid('delete'.$attributeProduct->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($attributeProduct);
            $entityManager->flush();
        }

        return $this->redirectToRoute('attribute_product_index');
    }
}

src/Controller/AttributeProductController.php
<?php

namespace App\Controller;

use App\Entity\AttributeProduct;
use App\Form\AttributeProductType;
use App\Repository\AttributeProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/attribute/product", name="product")
 */
class AttributeProductController extends AbstractController
{
    /**
     * @Route("/", name="attribute_product_index", methods={"GET"})
     * @param AttributeProductRepository $attributeProductRepository
     * @return Response
     */
    public function index(AttributeProductRepository $attributeProductRepository): Response
    {
        return $this->render('attribute_product/index.html.twig', [
            'attribute_products' => $attributeProductRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="attribute_product_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $attributeProduct = new AttributeProduct();
        $form = $this->createForm(AttributeProductType::class, $attributeProduct);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($attributeProduct);
            $entityManager->flush();

            return $this->redirectToRoute('attribute_product_index');
        }

        return $this->render('attribute_product/new.html.twig', [
            'attribute_product' => $attributeProduct,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="attribute_product_show", methods={"GET"})
     * @param AttributeProduct $attributeProduct
     * @return Response
     */
    public function show(AttributeProduct $attributeProduct): Response
    {
        return $this->render('attribute_product/show.html.twig', [
            'attribute_product' => $attributeProduct,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="attribute_product_edit", methods={"GET","POST"})
     * @param Request $request
     * @param AttributeProduct $attributeProduct
     * @return Response
     */
    public function edit(Request $request, AttributeProduct $attributeProduct): Response
    {
        $form = $this->createForm(AttributeProductType::class, $attributeProduct);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('attribute_product_index');
        }

        return $this->render('attribute_product/edit.html.twig', [
            'attribute_product' => $attributeProduct,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="attribute_product_delete", methods={"DELETE"})
     * @param Request $request
     * @param AttributeProduct $attributeProduct
     * @return Response
     */
    public function delete(Request $request, AttributeProduct $attributeProduct): Response
    {
        if ($this->isCsrfTokenValid('delete'.$attributeProduct->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($attributeProduct);
            $entityManager->flush();
        }

        return $this->redirectToRoute('attribute_product_index');
    }
}

templates/attribute_product/_delete_form.html.twig
<form method="post" action="{{ path('attribute_product_delete', {'id': attribute_product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ attribute_product.id) }}">
    <button class="btn">Delete</button>
</form>

templates/attribute_product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/attribute_product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit AttributeProduct{% endblock %}

{% block body %}
    <h1>Edit AttributeProduct</h1>

    {{ include('attribute_product/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('attribute_product_index') }}">back to list</a>

    {{ include('attribute_product/_delete_form.html.twig') }}
{% endblock %}

templates/attribute_product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}AttributeProduct index{% endblock %}

{% block body %}
    <h1>AttributeProduct index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Product_id</th>
                <th>Attribute_id</th>
                <th>Value</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for attribute_product in attribute_products %}
            <tr>
                <td>{{ attribute_product.id }}</td>
                <td>{{ attribute_product.productId }}</td>
                <td>{{ attribute_product.attributeId }}</td>
                <td>{{ attribute_product.value }}</td>
                <td>
                    <a href="{{ path('attribute_product_show', {'id': attribute_product.id}) }}">show</a>
                    <a href="{{ path('attribute_product_edit', {'id': attribute_product.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('attribute_product_new') }}">Create new</a>
{% endblock %}

templates/attribute_product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New AttributeProduct{% endblock %}

{% block body %}
    <h1>Create new AttributeProduct</h1>

    {{ include('attribute_product/_form.html.twig') }}

    <a href="{{ path('attribute_product_index') }}">back to list</a>
{% endblock %}

templates/attribute_product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}AttributeProduct{% endblock %}

{% block body %}
    <h1>AttributeProduct</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ attribute_product.id }}</td>
            </tr>
            <tr>
                <th>Product_id</th>
                <td>{{ attribute_product.productId }}</td>
            </tr>
            <tr>
                <th>Attribute_id</th>
                <td>{{ attribute_product.attributeId }}</td>
            </tr>
            <tr>
                <th>Value</th>
                <td>{{ attribute_product.value }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('attribute_product_index') }}">back to list</a>

    <a href="{{ path('attribute_product_edit', {'id': attribute_product.id}) }}">edit</a>

    {{ include('attribute_product/_delete_form.html.twig') }}
{% endblock %}