src/Entity/Categories.php
<?php

namespace App\Entity;

use App\Repository\CategoriesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use ShopBundle\Entity\Products;

/**
 * @ORM\Entity(repositoryClass=CategoriesRepository::class)
 */
class Categories
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $parent_id;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $level;

    /**
     * @ORM\Column(type="boolean")
     */
    private $enable;

    /**
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Product", inversedBy="categories")
     * @ORM\JoinTable(name="categories_products",
     *     joinColumns={
     *       @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     *     },
     *     inverseJoinColumns={
     *       @ORM\JoinColumn(name="product_id", referencedColumnName="id")
     *     }
     * )
     */
    protected $products;

    /**
     * @var
     * @ORM\OneToMany(targetEntity="App\Entity\ImagesCategories", mappedBy="images")
     */
    private $imagesCategories;

    public function __construct()
    {
        $this->products = new ArrayCollection();

    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getParentId(): ?int
    {
        return $this->parent_id;
    }

    public function setParentId(?int $parent_id): self
    {
        $this->parent_id = $parent_id;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(string $level): self
    {
        $this->level = $level;

        return $this;
    }
    public function getEnable(): ?bool
    {
        return $this->enable;
    }

    public function setEnable(bool $enable): self
    {
        $this->enable = $enable;

        return $this;
    }

    public function __toString()
    {
        return $this->getName();
    }

    public function getProducts()
    {
        return $this->products;
    }

    public function getImagesCategories()
    {
        return $this->imagesCategories;
    }
}

src/Form/CategoriesType.php
<?php

namespace App\Form;

use App\Entity\Categories;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoriesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('parent_id', EntityType::class, [
            'class' => Categories::class,
            'placeholder' => 'Choose an option',
            'required' => false,
        ])
            ->add('level')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Categories::class,
        ]);
    }
}

src/Admin/Controller/CategoriesController.php
<?php

namespace App\Admin\Controller;

use App\Entity\Categories;
use App\Form\CategoriesType;
use App\Repository\CategoriesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/categories")
 */
class CategoriesController extends AbstractController
{
    /**
     * @Route("/", name="categories_index", methods={"GET"})
     */
    public function index(CategoriesRepository $categoriesRepository): Response
    {
        return $this->render('admin/categories/index.html.twig', [
            'categories' => $categoriesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="categories_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $category = new Categories();
        $form = $this->createForm(CategoriesType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($category);
            $entityManager->flush();

            return $this->redirectToRoute('categories_index');
        }

        return $this->render('admin/categories/new.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="categories_show", methods={"GET"})
     */
    public function show(Categories $category): Response
    {
        return $this->render('admin/categories/show.html.twig', [
            'category' => $category,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="categories_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Categories $category): Response
    {
        $form = $this->createForm(CategoriesType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('categories_index');
        }

        return $this->render('admin/categories/edit.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="categories_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Categories $category): Response
    {
        if ($this->isCsrfTokenValid('delete'.$category->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($category);
            $entityManager->flush();
        }

        return $this->redirectToRoute('categories_index');
    }
}

src/Controller/CategoriesController.php
<?php

namespace App\Controller;

use App\Entity\Categories;
use App\Entity\Product;
use App\Form\CategoriesType;
use App\Repository\CategoriesRepository;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/categories")
 */
class CategoriesController extends AbstractController
{
    /**
     * @Route("/{categories}", name="categories")
     * @param Categories $categories
     * @param CategoriesRepository $categoriesRepository
     * @return Response
     * @throws NonUniqueResultException
     */

    public function categoriesView(Categories $categories, CategoriesRepository $categoriesRepository ): Response
    {
        $children = $categoriesRepository->findChildren($categories->getId());
        // select c.* from categories c where parent_id = id

        $subCategories = $categoriesRepository->findBy(['parent_id' => $categories->getId()]);
        return $this->render('categories/categories.html.twig', [
            'categories' => $categories,
            'children' => $children,
            'subcategories' => $subCategories
        ]);
    }

    /**
     * @Route("/{categories}/{childCategories}", name="categories_children")
     * @param Categories $categories
     * @param Categories $childCategories
     * @param CategoriesRepository $categoriesRepository
     * @return Response
     * @throws NonUniqueResultException
     */

    public function productViewChildren(Categories $categories, Categories $childCategories, CategoriesRepository $categoriesRepository ): Response
    {

        $subCategories = $categoriesRepository->subСategory($categories->getId());
        $children = $categoriesRepository->findChildren($categories->getId());

        return $this->render('categories/categories.html.twig', [
            'children' => $children,
            'categories' => $categories,
            'subcategories' => $subCategories,
            'childCategories' => $childCategories
        ]);
    }


}

templates/categories/_delete_form.html.twig
<form method="post" action="{{ path('categories_delete', {'id': category.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ category.id) }}">
    <button class="btn">Delete</button>
</form>

templates/categories/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/categories/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Categories{% endblock %}

{% block body %}
    <h1>Edit Categories</h1>

    {{ include('categories/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('categories_index') }}">back to list</a>

    {{ include('categories/_delete_form.html.twig') }}
{% endblock %}

templates/categories/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Categories index{% endblock %}

{% block body %}
    <h1>Categories index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Parent_id</th>
                <th>Level</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for category in categories %}
            <tr>
                <td>{{ category.id }}</td>
                <td>{{ category.name }}</td>
                <td>{{ category.parentId }}</td>
                <td>{{ category.level }}</td>
                <td>
                    <a href="{{ path('categories_show', {'id': category.id}) }}">show</a>
                    <a href="{{ path('categories_edit', {'id': category.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('categories_new') }}">Create new</a>
{% endblock %}

templates/categories/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Categories{% endblock %}

{% block body %}
    <h1>Create new Categories</h1>

    {{ include('categories/_form.html.twig') }}

    <a href="{{ path('categories_index') }}">back to list</a>
{% endblock %}

templates/categories/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Categories{% endblock %}

{% block body %}
    <h1>Categories</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ category.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ category.name }}</td>
            </tr>
            <tr>
                <th>Parent_id</th>
                <td>{{ category.parentId }}</td>
            </tr>
            <tr>
                <th>Level</th>
                <td>{{ category.level }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('categories_index') }}">back to list</a>

    <a href="{{ path('categories_edit', {'id': category.id}) }}">edit</a>

    {{ include('categories/_delete_form.html.twig') }}
{% endblock %}